### ISSUE TITLE
Error on start-zk

### ISSUE THREAD

**Issue by yanatan16** [ymilky/travel-zoo#2]
```
user=> (require '[travel-zoo.embedded.server :as server])
nil
user=> (require '[travel-zoo.embedded.protocols :refer [start-zk]])
nil
user=> (def s (server/make-embedded-zookeeper {:port 2181}))
#'user/s
user=> (start-zk s)
16-05-27 22:57:41 rl1gw2-194-165-dhcp.int.colorado.edu INFO [travel-zoo.embedded.server:20] - Starting Embedded Zookeeper server - 127.0.0.1:2181
Exception in thread "Thread-6" java.lang.NoSuchFieldError: configFileStr
    at org.apache.curator.test.QuorumConfigBuilder$1.<init>(QuorumConfigBuilder.java:135)
    at org.apache.curator.test.QuorumConfigBuilder.buildConfig(QuorumConfigBuilder.java:130)
    at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:149)
    at java.lang.Thread.run(Thread.java:745)
```

Any ideas?

**Comment by yanatan16** [comment]
Nevermind. I believe its an issue of two libraries including zookeeper.
